const weekData = {
  "396": [
    {
      "rank": 1,
      "movement": "NEW",
      "title": "Cry about it!",
      "artist": "Kali Uchis & Ravyn Lenae",
      "album": "Cry about it! - Single",
      "plays": 12,
      "sales": 473.40000000000003,
      "totalSales": 473.40000000000003,
      "weeks": 1,
      "peak": 1,
      "streams": 195159150,
      "radio": 88478460,
      "points": 200
    },
    {
      "rank": 2,
      "movement": "NEW",
      "title": "COMË N GO",
      "artist": "Yeat",
      "album": "DANGEROUS SUMMER",
      "plays": 9,
      "sales": 323.01,
      "totalSales": 323.01,
      "weeks": 1,
      "peak": 2,
      "streams": 133160872,
      "radio": 60370569,
      "points": 136
    },
    {
      "rank": 3,
      "movement": "NEW",
      "title": "Damage Control",
      "artist": "Jenevieve",
      "album": "Crysalis",
      "plays": 9,
      "sales": 323.01,
      "totalSales": 323.01,
      "weeks": 1,
      "peak": 3,
      "streams": 133160872,
      "radio": 60370569,
      "points": 136
    },
    {
      "rank": 4,
      "movement": "NEW",
      "title": "Nice Guy (feat. Tyla)",
      "artist": "Cardi B",
      "album": "AM I THE DRAMA?",
      "plays": 9,
      "sales": 323.01,
      "totalSales": 323.01,
      "weeks": 1,
      "peak": 4,
      "streams": 133160872,
      "radio": 60370569,
      "points": 136
    },
    {
      "rank": 5,
      "movement": "NEW",
      "title": "Sacrifice",
      "artist": "Mariah the Scientist",
      "album": "HEARTS SOLD SEPARATELY",
      "plays": 8,
      "sales": 287.12,
      "totalSales": 287.12,
      "weeks": 1,
      "peak": 5,
      "streams": 118365220,
      "radio": 53662728,
      "points": 121
    },
    {
      "rank": 6,
      "movement": "NEW",
      "title": "Safe (feat. Kehlani)",
      "artist": "Cardi B",
      "album": "AM I THE DRAMA?",
      "plays": 8,
      "sales": 257.28,
      "totalSales": 257.28,
      "weeks": 1,
      "peak": 6,
      "streams": 106063679,
      "radio": 48085632,
      "points": 109
    },
    {
      "rank": 7,
      "movement": "NEW",
      "title": "Naive",
      "artist": "Jenevieve",
      "album": "Crysalis",
      "plays": 8,
      "sales": 257.28,
      "totalSales": 257.28,
      "weeks": 1,
      "peak": 7,
      "streams": 106063679,
      "radio": 48085632,
      "points": 109
    },
    {
      "rank": 8,
      "movement": "NEW",
      "title": "Trust",
      "artist": "Brent Faiyaz",
      "album": "Lost - EP",
      "plays": 7,
      "sales": 225.11999999999998,
      "totalSales": 225.11999999999998,
      "weeks": 1,
      "peak": 8,
      "streams": 92805720,
      "radio": 42074928,
      "points": 95
    },
    {
      "rank": 9,
      "movement": "NEW",
      "title": "Nocturne",
      "artist": "Jenevieve",
      "album": "Crysalis",
      "plays": 7,
      "sales": 225.11999999999998,
      "totalSales": 225.11999999999998,
      "weeks": 1,
      "peak": 9,
      "streams": 92805720,
      "radio": 42074928,
      "points": 95
    },
    {
      "rank": 10,
      "movement": "NEW",
      "title": "Salute",
      "artist": "Cardi B",
      "album": "AM I THE DRAMA?",
      "plays": 6,
      "sales": 192.95999999999998,
      "totalSales": 192.95999999999998,
      "weeks": 1,
      "peak": 10,
      "streams": 79547760,
      "radio": 36064223.99999999,
      "points": 82
    },
    {
      "rank": 11,
      "movement": "NEW",
      "title": "Jealous Type",
      "artist": "Doja Cat",
      "album": "Vie",
      "plays": 6,
      "sales": 185.94,
      "totalSales": 185.94,
      "weeks": 1,
      "peak": 11,
      "streams": 76653765,
      "radio": 34752186,
      "points": 79
    },
    {
      "rank": 12,
      "movement": "NEW",
      "title": "Young Love",
      "artist": "Cleo Sol",
      "album": "Rose in the Dark",
      "plays": 6,
      "sales": 185.94,
      "totalSales": 185.94,
      "weeks": 1,
      "peak": 12,
      "streams": 76653765,
      "radio": 34752186,
      "points": 79
    },
    {
      "rank": 13,
      "movement": "NEW",
      "title": "SUGAR ON MY TONGUE",
      "artist": "Tyler, The Creator",
      "album": "DON'T TAP THE GLASS",
      "plays": 5,
      "sales": 154.95,
      "totalSales": 154.95,
      "weeks": 1,
      "peak": 13,
      "streams": 63878137,
      "radio": 28960155,
      "points": 65
    },
    {
      "rank": 14,
      "movement": "NEW",
      "title": "Bout Mine",
      "artist": "Mariah the Scientist",
      "album": "Bout Mine - Single",
      "plays": 5,
      "sales": 154.95,
      "totalSales": 154.95,
      "weeks": 1,
      "peak": 14,
      "streams": 63878137,
      "radio": 28960155,
      "points": 65
    },
    {
      "rank": 15,
      "movement": "NEW",
      "title": "DYNAMITE",
      "artist": "Tyla & Wizkid",
      "album": "WWP - Single",
      "plays": 5,
      "sales": 154.95,
      "totalSales": 154.95,
      "weeks": 1,
      "peak": 15,
      "streams": 63878137,
      "radio": 28960155,
      "points": 65
    },
    {
      "rank": 16,
      "movement": "NEW",
      "title": "Medallion",
      "artist": "Jenevieve",
      "album": "Division",
      "plays": 5,
      "sales": 154.95,
      "totalSales": 154.95,
      "weeks": 1,
      "peak": 16,
      "streams": 63878137,
      "radio": 28960155,
      "points": 65
    },
    {
      "rank": 17,
      "movement": "NEW",
      "title": "Can't Wait",
      "artist": "Doja Cat",
      "album": "Scarlet 2 CLAUDE",
      "plays": 5,
      "sales": 154.95,
      "totalSales": 154.95,
      "weeks": 1,
      "peak": 17,
      "streams": 63878137,
      "radio": 28960155,
      "points": 65
    },
    {
      "rank": 18,
      "movement": "NEW",
      "title": "Flow",
      "artist": "Sade",
      "album": "Lovers Rock",
      "plays": 4,
      "sales": 123.96,
      "totalSales": 123.96,
      "weeks": 1,
      "peak": 18,
      "streams": 51102509,
      "radio": 23168124,
      "points": 52
    },
    {
      "rank": 19,
      "movement": "NEW",
      "title": "OH I DID",
      "artist": "Yeat & NGeeYL",
      "album": "DANGEROUS SUMMER",
      "plays": 4,
      "sales": 123.96,
      "totalSales": 123.96,
      "weeks": 1,
      "peak": 19,
      "streams": 51102509,
      "radio": 23168124,
      "points": 52
    },
    {
      "rank": 20,
      "movement": "NEW",
      "title": "Iron Lung (Breathe In)",
      "artist": "Jenevieve",
      "album": "Crysalis",
      "plays": 4,
      "sales": 123.96,
      "totalSales": 123.96,
      "weeks": 1,
      "peak": 20,
      "streams": 51102509,
      "radio": 23168124,
      "points": 52
    },
    {
      "rank": 21,
      "movement": "NEW",
      "title": "IS IT",
      "artist": "Tyla",
      "album": "IS IT - Single",
      "plays": 4,
      "sales": 115.92,
      "totalSales": 115.92,
      "weeks": 1,
      "peak": 21,
      "streams": 47788020,
      "radio": 21665448,
      "points": 49
    },
    {
      "rank": 22,
      "movement": "NEW",
      "title": "Caution",
      "artist": "Rig",
      "album": "Caution - Single",
      "plays": 4,
      "sales": 115.92,
      "totalSales": 115.92,
      "weeks": 1,
      "peak": 22,
      "streams": 47788020,
      "radio": 21665448,
      "points": 49
    },
    {
      "rank": 23,
      "movement": "NEW",
      "title": "Why Oh Why",
      "artist": "Céline Dion",
      "album": "Let's Talk About Love",
      "plays": 4,
      "sales": 115.92,
      "totalSales": 115.92,
      "weeks": 1,
      "peak": 23,
      "streams": 47788020,
      "radio": 21665448,
      "points": 49
    },
    {
      "rank": 24,
      "movement": "NEW",
      "title": "Pretty & Petty",
      "artist": "Cardi B",
      "album": "AM I THE DRAMA?",
      "plays": 4,
      "sales": 115.92,
      "totalSales": 115.92,
      "weeks": 1,
      "peak": 24,
      "streams": 47788020,
      "radio": 21665448,
      "points": 49
    },
    {
      "rank": 25,
      "movement": "NEW",
      "title": "Killin You Hoes",
      "artist": "Cardi B",
      "album": "AM I THE DRAMA?",
      "plays": 4,
      "sales": 115.92,
      "totalSales": 115.92,
      "weeks": 1,
      "peak": 25,
      "streams": 47788020,
      "radio": 21665448,
      "points": 49
    },
    {
      "rank": 26,
      "movement": "NEW",
      "title": "ErrTime",
      "artist": "Cardi B",
      "album": "AM I THE DRAMA?",
      "plays": 4,
      "sales": 115.92,
      "totalSales": 115.92,
      "weeks": 1,
      "peak": 26,
      "streams": 47788020,
      "radio": 21665448,
      "points": 49
    },
    {
      "rank": 27,
      "movement": "NEW",
      "title": "Eternal Flame",
      "artist": "Mariah the Scientist",
      "album": "HEARTS SOLD SEPARATELY",
      "plays": 4,
      "sales": 115.92,
      "totalSales": 115.92,
      "weeks": 1,
      "peak": 27,
      "streams": 47788020,
      "radio": 21665448,
      "points": 49
    },
    {
      "rank": 28,
      "movement": "NEW",
      "title": "MR. MEDIA",
      "artist": "Tyla",
      "album": "WWP - Single",
      "plays": 4,
      "sales": 115.92,
      "totalSales": 115.92,
      "weeks": 1,
      "peak": 28,
      "streams": 47788020,
      "radio": 21665448,
      "points": 49
    },
    {
      "rank": 29,
      "movement": "NEW",
      "title": "Man of Your Word",
      "artist": "Cardi B",
      "album": "AM I THE DRAMA?",
      "plays": 4,
      "sales": 115.92,
      "totalSales": 115.92,
      "weeks": 1,
      "peak": 29,
      "streams": 47788020,
      "radio": 21665448,
      "points": 49
    },
    {
      "rank": 30,
      "movement": "NEW",
      "title": "Principal (feat. Janet Jackson)",
      "artist": "Cardi B",
      "album": "AM I THE DRAMA?",
      "plays": 4,
      "sales": 115.92,
      "totalSales": 115.92,
      "weeks": 1,
      "peak": 30,
      "streams": 47788020,
      "radio": 21665448,
      "points": 49
    },
    {
      "rank": 31,
      "movement": "NEW",
      "title": "Faded Lve",
      "artist": "Jenevieve",
      "album": "Crysalis",
      "plays": 4,
      "sales": 115.92,
      "totalSales": 115.92,
      "weeks": 1,
      "peak": 31,
      "streams": 47788020,
      "radio": 21665448,
      "points": 49
    },
    {
      "rank": 32,
      "movement": "NEW",
      "title": "love yourself (interlude) [Instrumental]",
      "artist": "XXXTENTACION",
      "album": "? (Deluxe)",
      "plays": 4,
      "sales": 115.92,
      "totalSales": 115.92,
      "weeks": 1,
      "peak": 32,
      "streams": 47788020,
      "radio": 21665448,
      "points": 49
    },
    {
      "rank": 33,
      "movement": "NEW",
      "title": "outta my mind",
      "artist": "Monsune",
      "album": "Tradition - EP",
      "plays": 4,
      "sales": 115.92,
      "totalSales": 115.92,
      "weeks": 1,
      "peak": 33,
      "streams": 47788020,
      "radio": 21665448,
      "points": 49
    },
    {
      "rank": 34,
      "movement": "NEW",
      "title": "HVN High",
      "artist": "Jenevieve",
      "album": "Crysalis",
      "plays": 4,
      "sales": 115.92,
      "totalSales": 115.92,
      "weeks": 1,
      "peak": 34,
      "streams": 47788020,
      "radio": 21665448,
      "points": 49
    },
    {
      "rank": 35,
      "movement": "NEW",
      "title": "Missing Persons",
      "artist": "Jenevieve",
      "album": "Crysalis",
      "plays": 4,
      "sales": 115.92,
      "totalSales": 115.92,
      "weeks": 1,
      "peak": 35,
      "streams": 47788020,
      "radio": 21665448,
      "points": 49
    },
    {
      "rank": 36,
      "movement": "NEW",
      "title": "Haiku",
      "artist": "Jenevieve",
      "album": "Crysalis",
      "plays": 4,
      "sales": 115.92,
      "totalSales": 115.92,
      "weeks": 1,
      "peak": 36,
      "streams": 47788020,
      "radio": 21665448,
      "points": 49
    },
    {
      "rank": 37,
      "movement": "NEW",
      "title": "Flight Risk",
      "artist": "Jenevieve",
      "album": "Crysalis",
      "plays": 4,
      "sales": 115.92,
      "totalSales": 115.92,
      "weeks": 1,
      "peak": 37,
      "streams": 47788020,
      "radio": 21665448,
      "points": 49
    },
    {
      "rank": 38,
      "movement": "NEW",
      "title": "Crysalis",
      "artist": "Jenevieve",
      "album": "Crysalis",
      "plays": 4,
      "sales": 115.92,
      "totalSales": 115.92,
      "weeks": 1,
      "peak": 38,
      "streams": 47788020,
      "radio": 21665448,
      "points": 49
    },
    {
      "rank": 39,
      "movement": "NEW",
      "title": "DISRESPECTFUL (feat. The Joy)",
      "artist": "Doja Cat",
      "album": "Scarlet 2 CLAUDE",
      "plays": 4,
      "sales": 115.92,
      "totalSales": 115.92,
      "weeks": 1,
      "peak": 39,
      "streams": 47788020,
      "radio": 21665448,
      "points": 49
    },
    {
      "rank": 40,
      "movement": "NEW",
      "title": "Skin in the Game",
      "artist": "Ava Max",
      "album": "Don't Click Play",
      "plays": 3,
      "sales": 86.94,
      "totalSales": 86.94,
      "weeks": 1,
      "peak": 40,
      "streams": 35841015,
      "radio": 16249086,
      "points": 37
    },
    {
      "rank": 41,
      "movement": "NEW",
      "title": "Pick It Up (feat. Selena Gomez)",
      "artist": "Cardi B",
      "album": "AM I THE DRAMA?",
      "plays": 3,
      "sales": 78.30000000000001,
      "totalSales": 78.30000000000001,
      "weeks": 1,
      "peak": 41,
      "streams": 32279175,
      "radio": 14634270.000000002,
      "points": 33
    },
    {
      "rank": 42,
      "movement": "NEW",
      "title": "Missed You (Bonus Track)",
      "artist": "The Weeknd",
      "album": "After Hours (Deluxe)",
      "plays": 3,
      "sales": 78.30000000000001,
      "totalSales": 78.30000000000001,
      "weeks": 1,
      "peak": 42,
      "streams": 32279175,
      "radio": 14634270.000000002,
      "points": 33
    },
    {
      "rank": 43,
      "movement": "NEW",
      "title": "Dead (feat. Summer Walker)",
      "artist": "Cardi B",
      "album": "AM I THE DRAMA?",
      "plays": 3,
      "sales": 78.30000000000001,
      "totalSales": 78.30000000000001,
      "weeks": 1,
      "peak": 43,
      "streams": 32279175,
      "radio": 14634270.000000002,
      "points": 33
    },
    {
      "rank": 44,
      "movement": "NEW",
      "title": "Trophies",
      "artist": "Cardi B",
      "album": "AM I THE DRAMA?",
      "plays": 3,
      "sales": 78.30000000000001,
      "totalSales": 78.30000000000001,
      "weeks": 1,
      "peak": 44,
      "streams": 32279175,
      "radio": 14634270.000000002,
      "points": 33
    },
    {
      "rank": 45,
      "movement": "NEW",
      "title": "[ADL IS COMING]",
      "artist": "Yeat",
      "album": "DANGEROUS SUMMER",
      "plays": 3,
      "sales": 78.30000000000001,
      "totalSales": 78.30000000000001,
      "weeks": 1,
      "peak": 45,
      "streams": 32279175,
      "radio": 14634270.000000002,
      "points": 33
    },
    {
      "rank": 46,
      "movement": "NEW",
      "title": "Magnet",
      "artist": "Cardi B",
      "album": "AM I THE DRAMA?",
      "plays": 3,
      "sales": 78.30000000000001,
      "totalSales": 78.30000000000001,
      "weeks": 1,
      "peak": 46,
      "streams": 32279175,
      "radio": 14634270.000000002,
      "points": 33
    },
    {
      "rank": 47,
      "movement": "NEW",
      "title": "Interlude",
      "artist": "The Thing About Noise",
      "album": "Texture",
      "plays": 3,
      "sales": 78.30000000000001,
      "totalSales": 78.30000000000001,
      "weeks": 1,
      "peak": 47,
      "streams": 32279175,
      "radio": 14634270.000000002,
      "points": 33
    },
    {
      "rank": 48,
      "movement": "NEW",
      "title": "Skin Tight (Alternate) [feat. Steve Lacy]",
      "artist": "Ravyn Lenae",
      "album": "Skin Tight (Alternate) [feat. Steve Lacy] - Single",
      "plays": 3,
      "sales": 78.30000000000001,
      "totalSales": 78.30000000000001,
      "weeks": 1,
      "peak": 48,
      "streams": 32279175,
      "radio": 14634270.000000002,
      "points": 33
    },
    {
      "rank": 49,
      "movement": "NEW",
      "title": "Love Quotes",
      "artist": "Jenevieve",
      "album": "Love Quotes - Single",
      "plays": 3,
      "sales": 78.30000000000001,
      "totalSales": 78.30000000000001,
      "weeks": 1,
      "peak": 49,
      "streams": 32279175,
      "radio": 14634270.000000002,
      "points": 33
    },
    {
      "rank": 50,
      "movement": "NEW",
      "title": "Life Will Be",
      "artist": "Cleo Sol",
      "album": "Gold",
      "plays": 3,
      "sales": 78.30000000000001,
      "totalSales": 78.30000000000001,
      "weeks": 1,
      "peak": 50,
      "streams": 32279175,
      "radio": 14634270.000000002,
      "points": 33
    },
    {
      "rank": 51,
      "movement": "NEW",
      "title": "Interlude",
      "artist": "Jimpster",
      "album": "Amour",
      "plays": 3,
      "sales": 71.34,
      "totalSales": 71.34,
      "weeks": 1,
      "peak": 51,
      "streams": 29409915,
      "radio": 13333446.000000002,
      "points": 30
    },
    {
      "rank": 52,
      "movement": "NEW",
      "title": "Why Don't You",
      "artist": "Cleo Sol",
      "album": "Rose in the Dark",
      "plays": 3,
      "sales": 71.34,
      "totalSales": 71.34,
      "weeks": 1,
      "peak": 52,
      "streams": 29409915,
      "radio": 13333446.000000002,
      "points": 30
    },
    {
      "rank": 53,
      "movement": "NEW",
      "title": "Perfect by Design",
      "artist": "Luna Elle",
      "album": "Perfect by Design - Single",
      "plays": 3,
      "sales": 71.34,
      "totalSales": 71.34,
      "weeks": 1,
      "peak": 53,
      "streams": 29409915,
      "radio": 13333446.000000002,
      "points": 30
    },
    {
      "rank": 54,
      "movement": "NEW",
      "title": "No Child Left Behind",
      "artist": "Kanye West",
      "album": "Donda (Deluxe)",
      "plays": 3,
      "sales": 71.34,
      "totalSales": 71.34,
      "weeks": 1,
      "peak": 54,
      "streams": 29409915,
      "radio": 13333446.000000002,
      "points": 30
    },
    {
      "rank": 55,
      "movement": "NEW",
      "title": "Moon",
      "artist": "Kanye West",
      "album": "Donda (Deluxe)",
      "plays": 3,
      "sales": 71.34,
      "totalSales": 71.34,
      "weeks": 1,
      "peak": 55,
      "streams": 29409915,
      "radio": 13333446.000000002,
      "points": 30
    },
    {
      "rank": 56,
      "movement": "NEW",
      "title": "Partycrasher",
      "artist": "Jenevieve",
      "album": "Crysalis",
      "plays": 3,
      "sales": 71.34,
      "totalSales": 71.34,
      "weeks": 1,
      "peak": 56,
      "streams": 29409915,
      "radio": 13333446.000000002,
      "points": 30
    },
    {
      "rank": 57,
      "movement": "NEW",
      "title": "Enter The Void",
      "artist": "Jenevieve",
      "album": "Crysalis",
      "plays": 3,
      "sales": 71.34,
      "totalSales": 71.34,
      "weeks": 1,
      "peak": 57,
      "streams": 29409915,
      "radio": 13333446.000000002,
      "points": 30
    },
    {
      "rank": 58,
      "movement": "NEW",
      "title": "ACKNOWLEDGE ME (feat. The Joy)",
      "artist": "Doja Cat",
      "album": "Scarlet 2 CLAUDE",
      "plays": 3,
      "sales": 71.34,
      "totalSales": 71.34,
      "weeks": 1,
      "peak": 58,
      "streams": 29409915,
      "radio": 13333446.000000002,
      "points": 30
    },
    {
      "rank": 59,
      "movement": "NEW",
      "title": "The Reason",
      "artist": "Céline Dion",
      "album": "Let's Talk About Love",
      "plays": 2,
      "sales": 47.56,
      "totalSales": 47.56,
      "weeks": 1,
      "peak": 59,
      "streams": 19606610,
      "radio": 8888964,
      "points": 20
    },
    {
      "rank": 60,
      "movement": "NEW",
      "title": "DA WIZARD",
      "artist": "Travis Scott",
      "album": "JACKBOYS 2",
      "plays": 2,
      "sales": 47.56,
      "totalSales": 47.56,
      "weeks": 1,
      "peak": 60,
      "streams": 19606610,
      "radio": 8888964,
      "points": 20
    },
    {
      "rank": 61,
      "movement": "NEW",
      "title": "Outside",
      "artist": "Cardi B",
      "album": "Outside - Single",
      "plays": 2,
      "sales": 42.12,
      "totalSales": 42.12,
      "weeks": 1,
      "peak": 61,
      "streams": 17363970,
      "radio": 7872228,
      "points": 18
    },
    {
      "rank": 62,
      "movement": "NEW",
      "title": "Tears",
      "artist": "Sabrina Carpenter",
      "album": "Man’s Best Friend",
      "plays": 2,
      "sales": 42.12,
      "totalSales": 42.12,
      "weeks": 1,
      "peak": 62,
      "streams": 17363970,
      "radio": 7872228,
      "points": 18
    },
    {
      "rank": 63,
      "movement": "NEW",
      "title": "With you",
      "artist": "RealestK",
      "album": "With You - Single",
      "plays": 2,
      "sales": 42.12,
      "totalSales": 42.12,
      "weeks": 1,
      "peak": 63,
      "streams": 17363970,
      "radio": 7872228,
      "points": 18
    },
    {
      "rank": 64,
      "movement": "NEW",
      "title": "Ruby",
      "artist": "Central Cee",
      "album": "Wild West",
      "plays": 2,
      "sales": 42.12,
      "totalSales": 42.12,
      "weeks": 1,
      "peak": 64,
      "streams": 17363970,
      "radio": 7872228,
      "points": 18
    },
    {
      "rank": 65,
      "movement": "NEW",
      "title": "Love Without Tragedy / Mother Mary",
      "artist": "Rihanna",
      "album": "Unapologetic (Deluxe Version)",
      "plays": 2,
      "sales": 42.12,
      "totalSales": 42.12,
      "weeks": 1,
      "peak": 65,
      "streams": 17363970,
      "radio": 7872228,
      "points": 18
    },
    {
      "rank": 66,
      "movement": "NEW",
      "title": "Sucks to Be My Ex",
      "artist": "Ava Max",
      "album": "Don't Click Play",
      "plays": 2,
      "sales": 42.12,
      "totalSales": 42.12,
      "weeks": 1,
      "peak": 66,
      "streams": 17363970,
      "radio": 7872228,
      "points": 18
    },
    {
      "rank": 67,
      "movement": "NEW",
      "title": "Remember the Time",
      "artist": "Michael Jackson",
      "album": "Dangerous",
      "plays": 2,
      "sales": 42.12,
      "totalSales": 42.12,
      "weeks": 1,
      "peak": 67,
      "streams": 17363970,
      "radio": 7872228,
      "points": 18
    },
    {
      "rank": 68,
      "movement": "NEW",
      "title": "Currents",
      "artist": "Drake",
      "album": "Honestly, Nevermind",
      "plays": 2,
      "sales": 42.12,
      "totalSales": 42.12,
      "weeks": 1,
      "peak": 68,
      "streams": 17363970,
      "radio": 7872228,
      "points": 18
    },
    {
      "rank": 69,
      "movement": "NEW",
      "title": "Casio",
      "artist": "Jungle",
      "album": "For Ever",
      "plays": 2,
      "sales": 42.12,
      "totalSales": 42.12,
      "weeks": 1,
      "peak": 69,
      "streams": 17363970,
      "radio": 7872228,
      "points": 18
    },
    {
      "rank": 70,
      "movement": "NEW",
      "title": "Friend Of Mine",
      "artist": "Kelly Price",
      "album": "Soul Of A Woman",
      "plays": 2,
      "sales": 42.12,
      "totalSales": 42.12,
      "weeks": 1,
      "peak": 70,
      "streams": 17363970,
      "radio": 7872228,
      "points": 18
    },
    {
      "rank": 71,
      "movement": "NEW",
      "title": "Needle (feat. Drake)",
      "artist": "Nicki Minaj",
      "album": "Pink Friday 2",
      "plays": 2,
      "sales": 41.98,
      "totalSales": 41.98,
      "weeks": 1,
      "peak": 71,
      "streams": 17306254,
      "radio": 7846062,
      "points": 18
    },
    {
      "rank": 72,
      "movement": "NEW",
      "title": "Something New (feat. Chris Brown)",
      "artist": "Zendaya",
      "album": "Something New (feat. Chris Brown) - Single",
      "plays": 2,
      "sales": 41.98,
      "totalSales": 41.98,
      "weeks": 1,
      "peak": 72,
      "streams": 17306254,
      "radio": 7846062,
      "points": 18
    },
    {
      "rank": 73,
      "movement": "NEW",
      "title": "Every Word",
      "artist": "Sade",
      "album": "Lovers Rock",
      "plays": 2,
      "sales": 41.98,
      "totalSales": 41.98,
      "weeks": 1,
      "peak": 73,
      "streams": 17306254,
      "radio": 7846062,
      "points": 18
    },
    {
      "rank": 74,
      "movement": "NEW",
      "title": "Saturday Love (feat. Alexander O'Neal)",
      "artist": "Cherrelle & Alexander O'Neal",
      "album": "High Priority",
      "plays": 2,
      "sales": 41.98,
      "totalSales": 41.98,
      "weeks": 1,
      "peak": 74,
      "streams": 17306254,
      "radio": 7846062,
      "points": 18
    },
    {
      "rank": 75,
      "movement": "NEW",
      "title": "Dead to Me",
      "artist": "Kali Uchis",
      "album": "Isolation",
      "plays": 2,
      "sales": 41.98,
      "totalSales": 41.98,
      "weeks": 1,
      "peak": 75,
      "streams": 17306254,
      "radio": 7846062,
      "points": 18
    },
    {
      "rank": 76,
      "movement": "NEW",
      "title": "Just a Stranger (feat. Steve Lacy)",
      "artist": "Kali Uchis",
      "album": "Isolation",
      "plays": 2,
      "sales": 41.98,
      "totalSales": 41.98,
      "weeks": 1,
      "peak": 76,
      "streams": 17306254,
      "radio": 7846062,
      "points": 18
    },
    {
      "rank": 77,
      "movement": "NEW",
      "title": "Am I Dreaming (feat. Akon)",
      "artist": "Kat DeLuna",
      "album": "9 Lives",
      "plays": 2,
      "sales": 41.98,
      "totalSales": 41.98,
      "weeks": 1,
      "peak": 77,
      "streams": 17306254,
      "radio": 7846062,
      "points": 18
    },
    {
      "rank": 78,
      "movement": "NEW",
      "title": "Better Than You (feat. Cash Cobain)",
      "artist": "Cardi B",
      "album": "AM I THE DRAMA?",
      "plays": 2,
      "sales": 41.98,
      "totalSales": 41.98,
      "weeks": 1,
      "peak": 78,
      "streams": 17306254,
      "radio": 7846062,
      "points": 18
    },
    {
      "rank": 79,
      "movement": "NEW",
      "title": "LOOSE LEAF",
      "artist": "Yeat",
      "album": "DANGEROUS SUMMER",
      "plays": 2,
      "sales": 41.98,
      "totalSales": 41.98,
      "weeks": 1,
      "peak": 79,
      "streams": 17306254,
      "radio": 7846062,
      "points": 18
    },
    {
      "rank": 80,
      "movement": "NEW",
      "title": "First Thing Smokin'",
      "artist": "Loony",
      "album": "First Thing Smokin' - Single",
      "plays": 2,
      "sales": 41.98,
      "totalSales": 41.98,
      "weeks": 1,
      "peak": 80,
      "streams": 17306254,
      "radio": 7846062,
      "points": 18
    },
    {
      "rank": 81,
      "movement": "NEW",
      "title": "Ring Ring Ring",
      "artist": "Tyler, The Creator",
      "album": "DON'T TAP THE GLASS",
      "plays": 2,
      "sales": 21.8,
      "totalSales": 21.8,
      "weeks": 1,
      "peak": 81,
      "streams": 8987050,
      "radio": 4074420,
      "points": 9
    },
    {
      "rank": 82,
      "movement": "NEW",
      "title": "Dead (feat. Summer  Walker)",
      "artist": "Cardi B",
      "album": "AM I THE DRAMA?",
      "plays": 2,
      "sales": 21.8,
      "totalSales": 21.8,
      "weeks": 1,
      "peak": 82,
      "streams": 8987050,
      "radio": 4074420,
      "points": 9
    },
    {
      "rank": 83,
      "movement": "NEW",
      "title": "On My Back (feat. Lourdiz)",
      "artist": "Cardi B",
      "album": "AM I THE DRAMA?",
      "plays": 2,
      "sales": 21.8,
      "totalSales": 21.8,
      "weeks": 1,
      "peak": 83,
      "streams": 8987050,
      "radio": 4074420,
      "points": 9
    },
    {
      "rank": 84,
      "movement": "NEW",
      "title": "Spread Thin",
      "artist": "Mariah the Scientist",
      "album": "Buckles Laboratories Presents: The Intermission - EP",
      "plays": 2,
      "sales": 21.8,
      "totalSales": 21.8,
      "weeks": 1,
      "peak": 84,
      "streams": 8987050,
      "radio": 4074420,
      "points": 9
    },
    {
      "rank": 85,
      "movement": "NEW",
      "title": "Love Is Pretty",
      "artist": "Haley Smalls",
      "album": "The Cure III",
      "plays": 2,
      "sales": 21.8,
      "totalSales": 21.8,
      "weeks": 1,
      "peak": 85,
      "streams": 8987050,
      "radio": 4074420,
      "points": 9
    },
    {
      "rank": 86,
      "movement": "NEW",
      "title": "walking away interlude",
      "artist": "Boxboys",
      "album": "walking away interlude - Single",
      "plays": 2,
      "sales": 21.8,
      "totalSales": 21.8,
      "weeks": 1,
      "peak": 86,
      "streams": 8987050,
      "radio": 4074420,
      "points": 9
    },
    {
      "rank": 87,
      "movement": "NEW",
      "title": "Exit Wounds",
      "artist": "Jenevieve",
      "album": "Division",
      "plays": 2,
      "sales": 21.8,
      "totalSales": 21.8,
      "weeks": 1,
      "peak": 87,
      "streams": 8987050,
      "radio": 4074420,
      "points": 9
    },
    {
      "rank": 88,
      "movement": "NEW",
      "title": "Come to Life",
      "artist": "Kanye West",
      "album": "Donda (Deluxe)",
      "plays": 2,
      "sales": 21.8,
      "totalSales": 21.8,
      "weeks": 1,
      "peak": 88,
      "streams": 8987050,
      "radio": 4074420,
      "points": 9
    },
    {
      "rank": 89,
      "movement": "NEW",
      "title": "Hurricane",
      "artist": "Kanye West",
      "album": "Donda (Deluxe)",
      "plays": 2,
      "sales": 21.8,
      "totalSales": 21.8,
      "weeks": 1,
      "peak": 89,
      "streams": 8987050,
      "radio": 4074420,
      "points": 9
    },
    {
      "rank": 90,
      "movement": "NEW",
      "title": "Head Over Heels",
      "artist": "Jenevieve",
      "album": "Crysalis",
      "plays": 2,
      "sales": 21.8,
      "totalSales": 21.8,
      "weeks": 1,
      "peak": 90,
      "streams": 8987050,
      "radio": 4074420,
      "points": 9
    },
    {
      "rank": 91,
      "movement": "NEW",
      "title": "Red Ruby Da Sleeze",
      "artist": "Nicki Minaj",
      "album": "Pink Friday 2",
      "plays": 2,
      "sales": 21.8,
      "totalSales": 21.8,
      "weeks": 1,
      "peak": 91,
      "streams": 8987050,
      "radio": 4074420,
      "points": 9
    },
    {
      "rank": 92,
      "movement": "NEW",
      "title": "Big Difference",
      "artist": "Nicki Minaj",
      "album": "Pink Friday 2",
      "plays": 2,
      "sales": 21.8,
      "totalSales": 21.8,
      "weeks": 1,
      "peak": 92,
      "streams": 8987050,
      "radio": 4074420,
      "points": 9
    },
    {
      "rank": 93,
      "movement": "NEW",
      "title": "Everybody (feat. Lil Uzi Vert)",
      "artist": "Nicki Minaj",
      "album": "Pink Friday 2",
      "plays": 2,
      "sales": 21.8,
      "totalSales": 21.8,
      "weeks": 1,
      "peak": 93,
      "streams": 8987050,
      "radio": 4074420,
      "points": 9
    },
    {
      "rank": 94,
      "movement": "NEW",
      "title": "Fallin 4 U",
      "artist": "Nicki Minaj",
      "album": "Pink Friday 2",
      "plays": 2,
      "sales": 21.8,
      "totalSales": 21.8,
      "weeks": 1,
      "peak": 94,
      "streams": 8987050,
      "radio": 4074420,
      "points": 9
    },
    {
      "rank": 95,
      "movement": "NEW",
      "title": "Hello",
      "artist": "Cardi B",
      "album": "AM I THE DRAMA?",
      "plays": 2,
      "sales": 21.8,
      "totalSales": 21.8,
      "weeks": 1,
      "peak": 95,
      "streams": 8987050,
      "radio": 4074420,
      "points": 9
    },
    {
      "rank": 96,
      "movement": "NEW",
      "title": "Flawless Remix (feat. Nicki Minaj)",
      "artist": "Beyoncé",
      "album": "BEYONCÉ (More Only) - EP",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 96,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 97,
      "movement": "NEW",
      "title": "Back To Me",
      "artist": "Rudimental & Jess Glynne",
      "album": "Back To Me - Single",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 97,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 98,
      "movement": "NEW",
      "title": "Bounce Bacc (Radio Edit)",
      "artist": "Lewie & Lil Mosey",
      "album": "Bounce Bacc (Radio Edit) - Single",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 98,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 99,
      "movement": "NEW",
      "title": "Gone Gone Gone (Original Demo Version)",
      "artist": "Madonna",
      "album": "Veronica Electronica",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 99,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 100,
      "movement": "NEW",
      "title": "Sugar Sweet (feat. Kehlani)",
      "artist": "Mariah Carey & Shenseea",
      "album": "Here For It All",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 100,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 101,
      "movement": "NEW",
      "title": "IRL (FEAT. SZA)",
      "artist": "Lizzo",
      "album": "MY FACE HURTS FROM SMILING",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 101,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 102,
      "movement": "NEW",
      "title": "Long Ago",
      "artist": "Mariah Carey",
      "album": "Daydream",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 102,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 103,
      "movement": "NEW",
      "title": "Come Back to Me",
      "artist": "Janet Jackson",
      "album": "Rhythm Nation 1814",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 103,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 104,
      "movement": "NEW",
      "title": "I'm Gonna Be Ready",
      "artist": "Yolanda Adams",
      "album": "Believe",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 104,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 105,
      "movement": "NEW",
      "title": "HUMBLE.",
      "artist": "Kendrick Lamar",
      "album": "DAMN.",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 105,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 106,
      "movement": "NEW",
      "title": "Burning",
      "artist": "Sam Smith",
      "album": "The Thrill of It All",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 106,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 107,
      "movement": "NEW",
      "title": "Paint the Town Red",
      "artist": "Doja Cat",
      "album": "Scarlet",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 107,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 108,
      "movement": "NEW",
      "title": "Lay Me Down",
      "artist": "Sam Smith",
      "album": "In the Lonely Hour",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 108,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 109,
      "movement": "NEW",
      "title": "I Wanna Be Down",
      "artist": "Brandy",
      "album": "Brandy",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 109,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 110,
      "movement": "NEW",
      "title": "B.E.D.",
      "artist": "Jacquees",
      "album": "Night Cap - EP",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 110,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 111,
      "movement": "NEW",
      "title": "Notice Me",
      "artist": "SZA",
      "album": "SOS",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 111,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 112,
      "movement": "NEW",
      "title": "Only One Road",
      "artist": "Céline Dion",
      "album": "The Colour of My Love",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 112,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 113,
      "movement": "NEW",
      "title": "Otaku Hot Girl",
      "artist": "Megan Thee Stallion",
      "album": "Megan",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 113,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 114,
      "movement": "NEW",
      "title": "Joy to the World",
      "artist": "Mariah Carey",
      "album": "Merry Christmas (Deluxe Anniversary Edition)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 114,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 115,
      "movement": "NEW",
      "title": "Standing on the Sun (feat. Mr. Vegas) [Remix]",
      "artist": "Beyoncé",
      "album": "BEYONCÉ (Platinum Edition)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 115,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 116,
      "movement": "NEW",
      "title": "Lay With Me",
      "artist": "Ebube",
      "album": "Lay With Me - Single",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 116,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 117,
      "movement": "NEW",
      "title": "Take Me (I'm Yours)",
      "artist": "Johnny Gill",
      "album": "Let's Get The Mood Right",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 117,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 118,
      "movement": "NEW",
      "title": "Love Takes Time",
      "artist": "Mariah Carey",
      "album": "Mariah Carey",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 118,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 119,
      "movement": "NEW",
      "title": "Hmhmm (feat. EST Gee)",
      "artist": "Chris Brown",
      "album": "Breezy",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 119,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 120,
      "movement": "NEW",
      "title": "Everybody",
      "artist": "Madonna",
      "album": "Celebration (Deluxe Version)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 120,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 121,
      "movement": "NEW",
      "title": "I Saw the Sign",
      "artist": "Swedish Hit Makers",
      "album": "I Saw the Sign - Single",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 121,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 122,
      "movement": "NEW",
      "title": "Truffle Butter (feat. Drake & Lil Wayne)",
      "artist": "Nicki Minaj",
      "album": "The Pinkprint",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 122,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 123,
      "movement": "NEW",
      "title": "Hot Girl Summer (feat. Nicki Minaj & Ty Dolla $ign)",
      "artist": "Megan Thee Stallion",
      "album": "Hot Girl Summer (feat. Nicki Minaj & Ty Dolla $ign) - Single",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 123,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 124,
      "movement": "NEW",
      "title": "Baby, You Make Me Crazy",
      "artist": "Sam Smith",
      "album": "The Thrill of It All",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 124,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 125,
      "movement": "NEW",
      "title": "1:59 (feat. Gunna)",
      "artist": "Normani",
      "album": "1:59 (feat. Gunna) - Single",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 125,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 126,
      "movement": "NEW",
      "title": "Pretty Please",
      "artist": "Dua Lipa",
      "album": "Future Nostalgia",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 126,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 127,
      "movement": "NEW",
      "title": "Hmmm (feat. Davido)",
      "artist": "Chris Brown",
      "album": "11:11 (Deluxe)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 127,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 128,
      "movement": "NEW",
      "title": "I Love You",
      "artist": "Céline Dion",
      "album": "Falling Into You",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 128,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 129,
      "movement": "NEW",
      "title": "Versace on the Floor",
      "artist": "Bruno Mars",
      "album": "24K Magic",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 129,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 130,
      "movement": "NEW",
      "title": "OKLOSER",
      "artist": "Doja Cat",
      "album": "Scarlet 2 CLAUDE",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 130,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 131,
      "movement": "NEW",
      "title": "For the Lover That I Lost",
      "artist": "Sam Smith",
      "album": "Love Goes",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 131,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 132,
      "movement": "NEW",
      "title": "Call On Me",
      "artist": "Janet Jackson & Nelly",
      "album": "20 Y.O.",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 132,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 133,
      "movement": "NEW",
      "title": "Vuli Ndlela",
      "artist": "Brenda Fassie",
      "album": "South  African Wedding Day Hits 2023",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 133,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 134,
      "movement": "NEW",
      "title": "Sucka Free",
      "artist": "Tyler, The Creator",
      "album": "DON'T TAP THE GLASS",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 134,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 135,
      "movement": "NEW",
      "title": "Faith",
      "artist": "The Weeknd",
      "album": "After Hours",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 135,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 136,
      "movement": "NEW",
      "title": "LEFTRIGHT",
      "artist": "Lizzo",
      "album": "MY FACE HURTS FROM SMILING",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 136,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 137,
      "movement": "NEW",
      "title": "PBT",
      "artist": "Travis Scott, Tyla & Vybz Kartel",
      "album": "JACKBOYS 2",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 137,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 138,
      "movement": "NEW",
      "title": "Fight for Me",
      "artist": "Ava Max",
      "album": "Don't Click Play",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 138,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 139,
      "movement": "NEW",
      "title": "Is It a Crime",
      "artist": "Mariah the Scientist & Kali Uchis",
      "album": "HEARTS SOLD SEPARATELY",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 139,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 140,
      "movement": "NEW",
      "title": "Out of Time (KAYTRANADA Remix)",
      "artist": "The Weeknd & KAYTRANADA",
      "album": "Dawn FM (Alternate World)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 140,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 141,
      "movement": "NEW",
      "title": "Immortality (feat. Bee Gees)",
      "artist": "Céline Dion",
      "album": "Let's Talk About Love",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 141,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 142,
      "movement": "NEW",
      "title": "Don't You Worry Baby (feat. Madison McFerrin)",
      "artist": "Tyler, The Creator",
      "album": "DON'T TAP THE GLASS",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 142,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 143,
      "movement": "NEW",
      "title": "It Depends (feat. Bryson Tiller)",
      "artist": "Chris Brown",
      "album": "It Depends (feat. Bryson Tiller) - Single",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 143,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 144,
      "movement": "NEW",
      "title": "Final Lullaby (Bonus Track)",
      "artist": "The Weeknd",
      "album": "After Hours (Deluxe)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 144,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 145,
      "movement": "NEW",
      "title": "By Your Side",
      "artist": "Sade",
      "album": "Lovers Rock",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 145,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 146,
      "movement": "NEW",
      "title": "Pyramids",
      "artist": "Frank Ocean",
      "album": "channel ORANGE",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 146,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 147,
      "movement": "NEW",
      "title": "Coming Home (Interlude)",
      "artist": "Kali Uchis",
      "album": "Isolation",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 147,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 148,
      "movement": "NEW",
      "title": "In My Dreams",
      "artist": "Kali Uchis",
      "album": "Isolation",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 148,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 149,
      "movement": "NEW",
      "title": "Nuestro Planeta (feat. Reykon)",
      "artist": "Kali Uchis",
      "album": "Isolation",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 149,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 150,
      "movement": "NEW",
      "title": "Tyrant (feat. Jorja Smith)",
      "artist": "Kali Uchis",
      "album": "Isolation",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 150,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 151,
      "movement": "NEW",
      "title": "Your Teeth in My Neck",
      "artist": "Kali Uchis",
      "album": "Isolation",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 151,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 152,
      "movement": "NEW",
      "title": "Flight 22",
      "artist": "Kali Uchis",
      "album": "Isolation",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 152,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 153,
      "movement": "NEW",
      "title": "Body Language (Intro)",
      "artist": "Kali Uchis",
      "album": "Isolation",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 153,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 154,
      "movement": "NEW",
      "title": "Too Little Too Late",
      "artist": "JoJo",
      "album": "The High Road",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 154,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 155,
      "movement": "NEW",
      "title": "Eh, Eh (Nothing Else I Can Say)",
      "artist": "Lady Gaga",
      "album": "The Fame Monster (Deluxe Edition)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 155,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 156,
      "movement": "NEW",
      "title": "Pretty Girl Rock",
      "artist": "Keri Hilson",
      "album": "No Boys Allowed (Deluxe Version)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 156,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 157,
      "movement": "NEW",
      "title": "Maybe (feat. JRemy & BobbyBass)",
      "artist": "Jay Sean",
      "album": "My Own Way",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 157,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 158,
      "movement": "NEW",
      "title": "Selfish (Main Version)",
      "artist": "Asia Cruise",
      "album": "Selfish - Single",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 158,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 159,
      "movement": "NEW",
      "title": "So Good Remix (Feat. Lil Wayne)",
      "artist": "Electrik Red",
      "album": "How To Be A Lady: Vol. 1",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 159,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 160,
      "movement": "NEW",
      "title": "We R Who We R",
      "artist": "Ke$ha",
      "album": "Cannibal (Expanded Edition)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 160,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 161,
      "movement": "NEW",
      "title": "Lay With You (Feat. Faith Evans)",
      "artist": "El DeBarge",
      "album": "Second Chance (Bonus Version)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 161,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 162,
      "movement": "NEW",
      "title": "Your Love Is My Drug",
      "artist": "Ke$ha",
      "album": "Animal (Expanded Edition)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 162,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 163,
      "movement": "NEW",
      "title": "House in LA",
      "artist": "Jungle",
      "album": "For Ever",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 163,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 164,
      "movement": "NEW",
      "title": "Cherry",
      "artist": "Jungle",
      "album": "For Ever",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 164,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 165,
      "movement": "NEW",
      "title": "Who Shot Ya",
      "artist": "The Notorious B.I.G.",
      "album": "The Notorious B.I.G.: Greatest Hits",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 165,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 166,
      "movement": "NEW",
      "title": "Move Ya Body",
      "artist": "Nina Sky",
      "album": "Nina Sky",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 166,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 167,
      "movement": "NEW",
      "title": "Slime You Out (feat. SZA)",
      "artist": "Drake",
      "album": "Slime You Out (feat. SZA) - Single",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 167,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 168,
      "movement": "NEW",
      "title": "Best Friends",
      "artist": "The Weeknd",
      "album": "Dawn FM",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 168,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 169,
      "movement": "NEW",
      "title": "Spite",
      "artist": "Omar Apollo",
      "album": "Spite - Single",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 169,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 170,
      "movement": "NEW",
      "title": "You Are Not Alone",
      "artist": "Michael Jackson",
      "album": "3 AM",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 170,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 171,
      "movement": "NEW",
      "title": "Touchdown",
      "artist": "Jacquees",
      "album": "Baby Making",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 171,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 172,
      "movement": "NEW",
      "title": "Best Thing I Never Had",
      "artist": "Beyoncé",
      "album": "4 (Expanded Edition)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 172,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 173,
      "movement": "NEW",
      "title": "American Teen",
      "artist": "Khalid",
      "album": "American Teen",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 173,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 174,
      "movement": "NEW",
      "title": "Anymore",
      "artist": "Whitney Houston",
      "album": "I'm Your Baby Tonight",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 174,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 175,
      "movement": "NEW",
      "title": "BROWN SKIN GIRL",
      "artist": "Beyoncé, SAINt JHN, Wizkid & Blue Ivy Carter",
      "album": "The Lion King: The Gift",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 175,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 176,
      "movement": "NEW",
      "title": "New Americana",
      "artist": "Halsey",
      "album": "BADLANDS (Deluxe Edition)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 176,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 177,
      "movement": "NEW",
      "title": "Touch (Acoustic)",
      "artist": "Little Mix",
      "album": "Glory Days: The Platinum Edition",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 177,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 178,
      "movement": "NEW",
      "title": "Alone",
      "artist": "Halsey",
      "album": "hopeless fountain kingdom (Deluxe)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 178,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 179,
      "movement": "NEW",
      "title": "Crying in the Club",
      "artist": "Camila Cabello",
      "album": "Crying in the Club - Single",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 179,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 180,
      "movement": "NEW",
      "title": "Bad at Love",
      "artist": "Halsey",
      "album": "hopeless fountain kingdom (Deluxe)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 180,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 181,
      "movement": "NEW",
      "title": "Colors",
      "artist": "Halsey",
      "album": "BADLANDS (Deluxe Edition)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 181,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 182,
      "movement": "NEW",
      "title": "Without Me",
      "artist": "Halsey",
      "album": "Manic",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 182,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 183,
      "movement": "NEW",
      "title": "Now or Never",
      "artist": "Halsey",
      "album": "hopeless fountain kingdom (Deluxe)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 183,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 184,
      "movement": "NEW",
      "title": "Never Be the Same",
      "artist": "Camila Cabello",
      "album": "Camila",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 184,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 185,
      "movement": "NEW",
      "title": "Havana (feat. Young Thug)",
      "artist": "Camila Cabello",
      "album": "Camila",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 185,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 186,
      "movement": "NEW",
      "title": "Real Friends (feat. Swae Lee)",
      "artist": "Camila Cabello",
      "album": "Real Friends (feat. Swae Lee) - Single",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 186,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 187,
      "movement": "NEW",
      "title": "Capital Letters",
      "artist": "Hailee Steinfeld & BloodPop®",
      "album": "Fifty Shades Freed (Original Motion Picture Soundtrack)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 187,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 188,
      "movement": "NEW",
      "title": "The Prologue",
      "artist": "Halsey",
      "album": "hopeless fountain kingdom (Deluxe)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 188,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 189,
      "movement": "NEW",
      "title": "Mr. Cool",
      "artist": "Tamia",
      "album": "More",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 189,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 190,
      "movement": "NEW",
      "title": "Poetry",
      "artist": "Tamia",
      "album": "More",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 190,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 191,
      "movement": "NEW",
      "title": "Laundromat (Radio Edit)",
      "artist": "Nivea",
      "album": "Nivea",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 191,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 192,
      "movement": "NEW",
      "title": "Rude",
      "artist": "MAGIC!",
      "album": "Don't Kill the Magic",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 192,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 193,
      "movement": "NEW",
      "title": "Champagne Shit",
      "artist": "Janelle Monáe",
      "album": "The Age of Pleasure",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 193,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 194,
      "movement": "NEW",
      "title": "F.U.C.K.",
      "artist": "Victoria Monét",
      "album": "F.U.C.K. - Single",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 194,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 195,
      "movement": "NEW",
      "title": "I Like That",
      "artist": "Janelle Monáe",
      "album": "Dirty Computer",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 195,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 196,
      "movement": "NEW",
      "title": "Wait a Minute!",
      "artist": "Willow",
      "album": "ARDIPITHECUS",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 196,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 197,
      "movement": "NEW",
      "title": "Crazy, Classic, Life",
      "artist": "Janelle Monáe",
      "album": "Dirty Computer",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 197,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 198,
      "movement": "NEW",
      "title": "Somebody That I Used to Know",
      "artist": "Gotye",
      "album": "Making Mirrors (Deluxe Edition)",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 198,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 199,
      "movement": "NEW",
      "title": "Yoga",
      "artist": "Janelle Monáe & Jidenna",
      "album": "Yoga - Single",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 199,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    },
    {
      "rank": 200,
      "movement": "NEW",
      "title": "Make Me Feel",
      "artist": "Janelle Monáe",
      "album": "Dirty Computer",
      "plays": 1,
      "sales": 10.9,
      "totalSales": 10.9,
      "weeks": 1,
      "peak": 200,
      "streams": 4493525,
      "radio": 2037210,
      "points": 5
    }
  ]
};

module.exports = weekData;
